apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
        app: tspproject
        tier: frontend
  template:
    metadata:
      labels:
        app: tspproject
        tier: frontend
    spec:
      containers:
      - name: phpapp
        image: habib02/tsp-projet-app:49
        imagePullPolicy: "Always"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: test
  labels:
    app: tspproject
    tier: test
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  #type: LoadBalancer
  type: NodePort
  ports:
    # the port that this service should serve on
  - port: 80
  selector:
    app: tspproject
    tier: frontend      
